### ISSUE TITLE
目标是https报错

### ISSUE THREAD

**Issue by GlobeMasterX** [theLSA/tp5-getshell#2]
目标是https报错

**Comment by theLSA** [comment]
错误信息是什么？

**Comment by mgiftdc** [comment]
C:\Python27\lib\site-packages\urllib3\connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Poc3 phpinfo checked fail! status code: 404

**Comment by theLSA** [comment]
因为没校验https（verify=False），所以出现这个警告，可忽略。
//requests.get(fullUrl,headers=headers,timeout=timeout,verify=False)
